CREATE USER repl_user WITH REPLICATION ENCRYPTED PASSWORD 'Qq123456' LOGIN;

CREATE DATABASE db_pt;
\c db_pt;

CREATE TABLE IF NOT EXISTS phones (id SERIAL PRIMARY KEY, phone VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS emails (id SERIAL PRIMARY KEY, email VARCHAR(255) NOT NULL);

INSERT INTO phones (id, phone) VALUES
(DEFAULT, '80001112233'),
(DEFAULT, '+79995550011');

INSERT INTO emails (id, email) VALUES
(DEFAULT, 'pt_user@gmail.com'),
(DEFAULT, 'average_pt_user@pt.ru');
